<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="bst/css/bootstrap.css" rel="stylesheet">
</head>
<body>
    <div class="container">
    <div class="card shadow">
    <div class="card-header">
    Data
    </div>
    <div class="card-body">
      <div class="table">
         <table class="table-hover">
       <tr>
       <td>Id</td>
       <td>Name</td>
       <td>Email</td>
       <td>Address</td>
       <td>Phone</td>
       </tr>
         </table>
      </div>
    </div>
    </div>
    </div>
    <script src="bst/js/bootstrap.js"></script>
</body>
</html>